version: "2.3"
services:
  sdc-program:
    runtime: nvidia
    build:
      context: ../sdc
      dockerfile: ../.devcontainer/Dockerfile
    user: koda
    working_dir: /home/koda

    network_mode: host

    ports:
      - "80:80"

    expose:
      - 80

    init: true
    privileged: true

    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - UDEV=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - ..:/workspace:cached

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock

      # Enable GUI environments
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      # Enable kernel modules (v4l2loopback)
      - /lib/modules:/lib/modules

      # Enable creating/reading inside docker new devices
      - /dev:/dev

    # Add devices to be share in container
    devices:
      - /dev/bus/usb:/dev/bus/usb

      # NVIDIA drivers to use OpenGL, etc...
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/input:/dev/input
      - /dev/snd:/dev/snd

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # command: sleep infinity 
    stdin_open: true
    tty: true

    command: "/bin/bash"
